version: 0.2
env:
  parameter-store:
     DOCKER_REGISTRY_USERNAME: /python-demo/docker-credential/username
     DOCKER_REGISTRY_PASSWORD: /python-demo/docker-credential/password
     DOCKER_REGISTRY_URL: /python-demo/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install -r simple-python-app/requirements.txt
  
  build:
    commands:
      - cd simple-python-app
      - echo "Building the docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/flask-app:v1" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/flask-app:v1"
      
  post_build:
    commands:
     - echo "Build is success"
